### ISSUE TITLE
Set CODECOV_TOKEN for repo

### ISSUE THREAD

**Issue by MasterOdin** [py-pdf/pypdf_table_extraction#62]
While #29 was closed with updating the `codecov/codecov-action`, it appears the repo was not yet setup with a `CODECOV_TOKEN`. See https://github.com/py-pdf/pypdf_table_extraction/actions/runs/10488522333/job/29051313824 as an example (latest run of the coverage workflow for `main`), where the upload step outputs:

```
Error: Codecov token not found. Please provide Codecov token with -t flag.
```

Further, if expand the first line of that step of the job:

```
Run codecov/codecov-action@v4
  with:
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.14/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
    Python[2](https://github.com/py-pdf/pypdf_table_extraction/actions/runs/10488522333/job/29051313824#step:10:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/py-pdf/pypdf_table_extraction/actions/runs/10488522333/job/29051313824#step:10:3).10.1[4](https://github.com/py-pdf/pypdf_table_extraction/actions/runs/10488522333/job/29051313824#step:10:4)/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib
    CODECOV_TOKEN:
```

where we can see that no value was passed in for `CODECOV_TOKEN`.

As such, I think someone still needs to actually set `${{ secrets.CODECOV_TOKEN }}` to a value for this to work. See https://docs.codecov.com/docs/adding-the-codecov-token for instructions on how to do this.
